exports.USER_STATUS_WAITING_VERIFYING = 0;
exports.USER_STATUS_ACTIVE = 1;
exports.USER_STATUS_BLOCKED = 2;

exports.USER_GENDER_FEMALE = 0;
exports.USER_GENDER_MALE = 1;

exports.ADMIN_STATUS_WAITING_VERIFYING = 0;
exports.ADMIN_STATUS_ACTIVE = 1;
exports.ADMIN_STATUS_BLOCKED = 2;
